--- #YAML:1.0
name:                     Test-CPAN-Meta-YAML
version:                  0.20
abstract:                 A test module to validate a CPAN META.yml file.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  Test::YAML::Valid:      0.03
  Test::More:             0.70
  Test::Builder:          0
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::YAML::Valid:      0.03
  YAML:                   0
  YAML::Syck:             0
build_requires:
  Test::More:             0.70
  Test::Builder::Tester:  0

provides:
  Test::CPAN::Meta::YAML:
    file:     lib/Test/CPAN/Meta/YAML.pm
    version:  0.20
  Test::CPAN::Meta::YAML::Version:
    file:     lib/Test/CPAN/Meta/YAML/Version.pm
    version:  0.20
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-CPAN-Meta-YAML

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
